#!/usr/bin/php
<?php
include 'credentials.php';
include 'OpenPhotoOAuth.php';
$output = Array();
$status = 1;
$output2 = Array();
$status2 = 1;
$client = new OpenPhotoOAuth($host, $consumerKey, $consumerSecret, $token, $tokenSecret);


function normalizePath($path){
		$path2 = addcslashes($path,' "\'');
		return $path2;
}

function getName($path){
	$array = explode('/',$path);
	$name = $array[count($array) - 1];
	$array = explode ('.',$name);
	$name = $array[0];
	$name = stripcslashes($name);
	return $name;
}

exec("cd $repo; git diff-tree --name-status -r -z photoView master", $output, $status);
if($status == 0){
	$matches = preg_split('/\0/', $output[0]);
	for($i = 0, $size = count($matches) - 2; $i < $size; ++$i) {
		$mode = $matches[$i];
		++$i;
		$linkName = $matches[$i];
		$linkNameSh = normalizePath($linkName);
		exec("cd $repo; git checkout master $linkNameSh; git annex get $linkNameSh", $output2,$status2);
		$linkPath = sprintf('%1$s/%2$s',$repo,$linkName);
		$photoPath = sprintf('%1$s/%2$s',$repo,file_get_contents($linkPath));
		$photoBase64Encoded = base64_encode(file_get_contents($photoPath));
		$response = $client->post("/photo/upload.json", array('photo' => $photoBase64Encoded, 
			'title' => getName($linkNameSh),
			'permission' => "1",
			'tags' => "git-annex",
			'appId' => "Git-annex" ));
		exec("cd $repo; rm $linkNameSh;", $output2,$status2);
		echo "\n";
		echo $response;
		echo "\n";

	}

} 

